### ISSUE TITLE
表单组件dateRange，timeRange不支持,程序报错！

### ISSUE THREAD

**Issue by yany88** [ichynul/row-table#2]
作者你好，我使用提laravel-admin1.7.7版本，在使用表单dateRange，timeRange组件时报错，貌似是不支持，能否修复一下。

**Comment by yany88** [comment]
作者你好，我测试貌似还有点问题，报如下错误：
![微信图片_20191130103930](https://user-images.githubusercontent.com/9587112/69894670-bce17580-135d-11ea-9d54-982162785be5.png)
然后我找到了/ichynul/row-table/src/table.php文件加了如下代码，问题解决了，作者能更新一下吗
![微信截图_20191130104101](https://user-images.githubusercontent.com/9587112/69894700-04680180-135e-11ea-8b04-59d6c4915703.png)

**Comment by ichynul** [comment]
修改了，你更新一下看看
