### ISSUE TITLE
multipleImage追加图片会清空之前的图片，排序会导致图片为空

### ISSUE THREAD

**Issue by yany88** [ichynul/row-table#5]
作者您好，首先感谢您提供这么好用优秀的扩展库！
我在项目中使用本扩展时，发现使用multipleImage表单组件追加图片会清空原先的图片以及排序会导致图片为空，改用原生的$from->multipleImage就不会有问题，代码如下：
![image](https://user-images.githubusercontent.com/9587112/77027521-6f9f1780-69d1-11ea-9574-7ef14389f297.png)

模型里的代码：
![image](https://user-images.githubusercontent.com/9587112/77027560-8cd3e600-69d1-11ea-9807-b924f11ceb39.png)

我的环境：
php: 7.3
laravel:7.0

**Comment by ichynul** [comment]
已经提交了修复，你升级到最新版看看

**Comment by yany88** [comment]
> 已经提交了修复，你升级到最新版看看

谢谢作者，更新已经解决！
