### ISSUE TITLE
升级laravel-admin1.8.1后，radio和select组件出错！

### ISSUE THREAD

**Issue by yany88** [ichynul/row-table#6]
作者您好，今天升级了laravel-admin1.8.1后，出现radio和select组件无法正常使用，能否修复一下,报错如下:
![微信图片_20200529210932](https://user-images.githubusercontent.com/9587112/83263150-b8085c00-a1f0-11ea-8589-44d3791c2a6d.png)

我环境是：
    操作系统：centos 7
    PHP版本：7.2.13
    laravel:6.14

**Comment by yany88** [comment]
作者您好，更新最新版本后，使用Encore\Admin\Form构建的表单没有问题了，但是发现另外一个问题就是使用Encore\Admin\Widgets\Form构建的表单还是报同样的错误，能否再看一下？

**Comment by ichynul** [comment]
最后能提供一下报错截图，也许能直接看出来哪里有问题。

**Comment by yany88** [comment]
作者您好，我的代码和报错截图是这样的：
下面这种写法更新你的最新版本之后没有问题了：
![微信图片_20200605161711](https://user-images.githubusercontent.com/9587112/83853651-2ba5ee00-a748-11ea-826f-8a790a9f9e90.png)
如果是Encore\Admin\Widgets\Form构建表单的写法就会有问题：
![QQ截图20200605161351](https://user-images.githubusercontent.com/9587112/83853716-437d7200-a748-11ea-93ae-bc6db54e79e7.jpg)
报错如下：
![QQ截图20200605161259](https://user-images.githubusercontent.com/9587112/83853757-51cb8e00-a748-11ea-8d94-956d6fa85b16.jpg)

**Comment by ichynul** [comment]
修改了一下，你升级看看

**Comment by yany88** [comment]
升级后报了另外一个错误：
![QQ截图20200608094355](https://user-images.githubusercontent.com/9587112/83985695-c0893100-a96c-11ea-8500-131b319ed35f.jpg)
我加了如下代码，暂时得以解决：
![image](https://user-images.githubusercontent.com/9587112/83985726-d991e200-a96c-11ea-9a70-fd5cc7921641.png)

**Comment by ichynul** [comment]
修改了

**Comment by yany88** [comment]
非常感谢！
